### ISSUE TITLE
logo and loader issue 

### ISSUE THREAD

**Issue by ShubhamGore12** [ypo777/ypo777.github.io#2]
How did you change the logo and loader? can you tell me? 
I'm having an issue changing it just let me know which tool you have used.
It would be very helpful for me.

Thanks

**Comment by ypo777** [comment]
You can check [here](https://github.com/ypo777/ypo777.github.io/commit/87f3b14415e529b0d42df13c3fbf92629c4b0234)

**Comment by ShubhamGore12** [comment]
thank ...
